#!/usr/bin/env python3
"""Generate the target-side path-policy table from canonical sd-layout.toml."""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import sys
import tempfile
from typing import Sequence

from update_path_policy import (
    DEFAULT_POLICY_PATH,
    PolicySpecError,
    UpdatePathPolicy,
    load_update_path_policy,
)


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT_PATH = ROOT / "src/update/generated/update_path_policy_v1.h"


_KINDS = {
    "exact-path": "ExactPath",
    "top-root": "TopRoot",
    "basename-exact": "BasenameExact",
    "basename-prefix-suffix": "BasenamePrefixSuffix",
    "basename-suffix": "BasenameSuffix",
    "machine-kernel": "MachineKernel",
}
_POLICIES = {
    "config-template": "ConfigTemplate",
    "kernel": "Kernel",
    "managed-replace": "ManagedReplace",
    "metadata": "Metadata",
    "preserve": "Preserve",
}


def _cpp_string(value: str | None) -> str:
    if value is None:
        return "0"
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_header(policy: UpdatePathPolicy) -> str:
    lines = [
        "// Generated by tools/generate_update_path_policy.py.",
        "// DO NOT EDIT: change sd-layout.toml instead.",
        f"// Canonical policy SHA-256: {policy.source_sha256}",
        "#ifndef BMX_UPDATE_GENERATED_UPDATE_PATH_POLICY_V1_H",
        "#define BMX_UPDATE_GENERATED_UPDATE_PATH_POLICY_V1_H",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "namespace bmx {",
        "namespace update {",
        "namespace generated_path_policy_v1 {",
        "",
        "enum class RuleKind : uint8_t {",
        "    ExactPath = 0,",
        "    TopRoot,",
        "    BasenameExact,",
        "    BasenamePrefixSuffix,",
        "    BasenameSuffix,",
        "    MachineKernel",
        "};",
        "",
        "enum class RulePolicy : uint8_t {",
        "    ConfigTemplate = 0,",
        "    Kernel,",
        "    ManagedReplace,",
        "    Metadata,",
        "    Preserve",
        "};",
        "",
        "struct Rule {",
        "    RuleKind kind;",
        "    RulePolicy policy;",
        "    const char *root;",
        "    const char *value;",
        "    const char *suffix;",
        "};",
        "",
        f'static const char kSourceSha256[] = "{policy.source_sha256}";',
        "",
        "static const Rule kFileRules[] = {",
    ]
    for rule in policy.rules:
        policy_name = _POLICIES[rule.policy or policy.kernel_policy]
        lines.append(
            "    {RuleKind::%s, RulePolicy::%s, %s, %s, %s},"
            % (
                _KINDS[rule.kind],
                policy_name,
                _cpp_string(rule.root),
                _cpp_string(rule.value),
                _cpp_string(rule.suffix),
            )
        )
    lines.extend(
        [
            "};",
            "static const size_t kFileRuleCount =",
            "    sizeof(kFileRules) / sizeof(kFileRules[0]);",
            "",
            "static const char *const kDirectoryRoots[] = {",
        ]
    )
    lines.extend(f"    {_cpp_string(root)}," for root in policy.directory_roots)
    lines.extend(
        [
            "};",
            "static const size_t kDirectoryRootCount =",
            "    sizeof(kDirectoryRoots) / sizeof(kDirectoryRoots[0]);",
            "",
            "static const char *const kMachineKernelBases[] = {",
        ]
    )
    lines.extend(f"    {_cpp_string(base)}," for base in policy.kernel_bases)
    lines.extend(
        [
            "};",
            "static const size_t kMachineKernelBaseCount =",
            "    sizeof(kMachineKernelBases) / sizeof(kMachineKernelBases[0]);",
            "",
            "static const char *const kMachineKernelMachines[] = {",
        ]
    )
    lines.extend(f"    {_cpp_string(machine)}," for machine in policy.kernel_machines)
    lines.extend(
        [
            "};",
            "static const size_t kMachineKernelMachineCount =",
            "    sizeof(kMachineKernelMachines) / sizeof(kMachineKernelMachines[0]);",
            "static const size_t kRequiredKernelMachineCount = "
            f"{len(policy.required_kernel_machines)}U;",
            "",
            "static const RulePolicy kMachineKernelPolicy = RulePolicy::"
            f"{_POLICIES[policy.kernel_policy]};",
            "",
            "}  // namespace generated_path_policy_v1",
            "}  // namespace update",
            "}  // namespace bmx",
            "",
            "#endif  // BMX_UPDATE_GENERATED_UPDATE_PATH_POLICY_V1_H",
            "",
        ]
    )
    return "\n".join(lines)


def _write_if_changed(path: Path, encoded: bytes) -> None:
    try:
        if path.read_bytes() == encoded:
            return
    except FileNotFoundError:
        pass
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", dir=path.parent
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "wb") as output:
            output.write(encoded)
            output.flush()
            os.fsync(output.fileno())
        os.chmod(temporary, 0o644)
        os.replace(temporary, path)
    finally:
        try:
            temporary.unlink()
        except FileNotFoundError:
            pass


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--policy", type=Path, default=DEFAULT_POLICY_PATH)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT_PATH)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail without writing when the generated header is absent or stale",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    try:
        policy = load_update_path_policy(args.policy)
        encoded = render_header(policy).encode("ascii")
        if args.check:
            try:
                current = args.output.read_bytes()
            except OSError as exc:
                print(
                    "generate_update_path_policy.py: error: generated header is "
                    f"missing: {args.output} ({exc})",
                    file=sys.stderr,
                )
                return 1
            if current != encoded:
                print(
                    "generate_update_path_policy.py: error: generated header is stale; "
                    "run tools/generate_update_path_policy.py",
                    file=sys.stderr,
                )
                return 1
            return 0
        _write_if_changed(args.output, encoded)
        return 0
    except (OSError, PolicySpecError, UnicodeError) as exc:
        print(f"generate_update_path_policy.py: error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
